# CatBoost — Predicting Smartphone Addiction (Playground Series S6E8)

**Target:** `addicted_label` (binary)
**Metric:** AUC-ROC

This notebook trains a CatBoost classifier with native categorical handling for `gender`, `stress_level`, and `academic_work_impact`, using stratified 10-fold cross-validation.

## 1. Imports

In [1]:
import numpy as np
import pandas as pd
from catboost import CatBoostClassifier, Pool
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score
import matplotlib.pyplot as plt

# matplotlib backend for headless batch execution on Snellius
import matplotlib
matplotlib.use("Agg")

## 2. Load data

Paths point to the local data directory on Snellius. Adjust `DATA_DIR` if your files live elsewhere.

In [2]:
import os

DATA_DIR = os.environ.get("DATA_DIR", os.path.join(os.getcwd(), "data"))

TRAIN_PATH = os.path.join(DATA_DIR, "train.csv")
TEST_PATH = os.path.join(DATA_DIR, "test.csv")

train = pd.read_csv(TRAIN_PATH)
test = pd.read_csv(TEST_PATH)

print(train.shape, test.shape)
train.head()

(691369, 14) (296302, 13)

,id,age,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,gender,stress_level,academic_work_impact,addicted_label
0,0,24.0,NaN,1.83,1.59,2.11,7.46,122.0,38.0,8.63,Male,Medium,No,1
1,1,19.0,5.97,1.08,NaN,3.03,8.22,76.0,19.0,NaN,Female,Medium,No,0
2,2,18.0,5.09,NaN,NaN,NaN,6.25,134.0,60.0,7.47,Female,Low,Yes,0
3,3,21.0,6.42,1.26,1.42,3.36,8.85,112.0,94.0,8.66,Other,Low,NaN,1
4,4,26.0,11.20,1.87,2.81,1.95,5.25,NaN,NaN,13.39,Female,Medium,No,1

## 3. Define features and target

In [3]:
TARGET = "addicted_label"
ID_COL = "id" if "id" in train.columns else train.columns[0]

CAT_FEATURES = ["gender", "stress_level", "academic_work_impact"]

# Everything else (minus id/target) is treated as numeric
NUM_FEATURES = [
    c for c in train.columns
    if c not in CAT_FEATURES + [TARGET, ID_COL]
]

FEATURES = NUM_FEATURES + CAT_FEATURES
print("Numeric features:", NUM_FEATURES)
print("Categorical features:", CAT_FEATURES)

Numeric features: ['age', 'daily_screen_time_hours', 'social_media_hours', 'gaming_hours', 'work_study_hours', 'sleep_hours', 'notifications_per_day', 'app_opens_per_day', 'weekend_screen_time']
Categorical features: ['gender', 'stress_level', 'academic_work_impact']

## 4. Quick EDA

Class balance and a peek at the categorical/numeric distributions.

In [4]:
print(train[TARGET].value_counts(normalize=True))
train[TARGET].value_counts().plot(kind="bar", title="Class balance: addicted_label")
plt.savefig("class_balance.png", bbox_inches="tight")
plt.close()

addicted_label
1    0.709424
0    0.290576
Name: proportion, dtype: float64

In [5]:
train[NUM_FEATURES].describe().T

,count,mean,std,min,25%,50%,75%,max
age,662440.0,26.615408,5.153162,18.00,22.00,27.00,31.00,35.00
daily_screen_time_hours,595515.0,7.640865,2.721446,0.50,5.48,7.77,9.84,15.00
social_media_hours,557374.0,2.471038,1.316137,0.00,1.45,2.31,3.37,8.00
gaming_hours,564548.0,1.459265,0.934552,0.00,0.70,1.33,2.09,4.00
work_study_hours,639851.0,2.366971,1.258797,0.00,1.36,2.20,3.20,6.00
sleep_hours,646889.0,6.804334,1.234512,4.50,5.78,6.80,7.87,9.00
notifications_per_day,623785.0,145.894900,65.917556,20.00,93.00,150.00,204.00,250.00
app_opens_per_day,610659.0,102.636781,48.093970,15.00,64.00,104.00,145.00,180.00
weekend_screen_time,579306.0,9.479866,2.856006,0.51,7.28,9.58,11.75,17.56

## 5. Prep for CatBoost

CatBoost needs categorical columns as strings (not floats/NaN-as-float) and takes their column indices via `cat_features`.

In [6]:
for col in CAT_FEATURES:
    train[col] = train[col].fillna("missing").astype(str)
    test[col] = test[col].fillna("missing").astype(str)

X = train[FEATURES]
y = train[TARGET]
X_test = test[FEATURES]

cat_feature_idx = [X.columns.get_loc(c) for c in CAT_FEATURES]
cat_feature_idx

[9, 10, 11]

## 6. Stratified 10-fold CV training

Stratification keeps the class ratio consistent per fold. `eval_metric="AUC"` with early stopping optimizes directly for the competition metric.

In [7]:
N_SPLITS = 10
skf = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=42)

oof_preds = np.zeros(len(X))
test_preds = np.zeros(len(X_test))
fold_scores = []
models = []

params = dict(
    loss_function="Logloss",
    eval_metric="AUC",
    iterations=3000,
    learning_rate=0.03,
    depth=6,
    l2_leaf_reg=3.0,
    random_seed=42,
    early_stopping_rounds=200,
    verbose=200,
    task_type="GPU",
    devices="0",
)

for fold, (train_idx, val_idx) in enumerate(skf.split(X, y)):
    X_train, X_val = X.iloc[train_idx], X.iloc[val_idx]
    y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]

    train_pool = Pool(X_train, y_train, cat_features=cat_feature_idx)
    val_pool = Pool(X_val, y_val, cat_features=cat_feature_idx)
    test_pool = Pool(X_test, cat_features=cat_feature_idx)

    model = CatBoostClassifier(**params)
    model.fit(train_pool, eval_set=val_pool, use_best_model=True)
    models.append(model)

    val_pred = model.predict_proba(val_pool)[:, 1]
    oof_preds[val_idx] = val_pred

    fold_auc = roc_auc_score(y_val, val_pred)
    fold_scores.append(fold_auc)
    print(f"Fold {fold}: AUC = {fold_auc:.5f}")

    test_preds += model.predict_proba(test_pool)[:, 1] / N_SPLITS

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.9058316	best: 0.9058316 (0)	total: 34.8ms	remaining: 1m 44s

200:	test: 0.9364746	best: 0.9364746 (200)	total: 3.18s	remaining: 44.3s

400:	test: 0.9425056	best: 0.9425056 (400)	total: 6.3s	remaining: 40.9s

600:	test: 0.9461851	best: 0.9461851 (600)	total: 9.47s	remaining: 37.8s

800:	test: 0.9489059	best: 0.9489059 (800)	total: 12.6s	remaining: 34.6s

1000:	test: 0.9508334	best: 0.9508334 (1000)	total: 15.8s	remaining: 31.6s

1200:	test: 0.9522666	best: 0.9522666 (1200)	total: 19s	remaining: 28.5s

1400:	test: 0.9533707	best: 0.9533707 (1399)	total: 22.2s	remaining: 25.4s

1600:	test: 0.9542528	best: 0.9542528 (1600)	total: 25.4s	remaining: 22.2s

1800:	test: 0.9549263	best: 0.9549263 (1800)	total: 28.6s	remaining: 19s

2000:	test: 0.9555084	best: 0.9555084 (2000)	total: 31.8s	remaining: 15.9s

2200:	test: 0.9559592	best: 0.9559592 (2200)	total: 35s	remaining: 12.7s

2400:	test: 0.9563527	best: 0.9563528 (2399)	total: 38.2s	remaining: 9.54s

2600:	test: 0.9566482	best: 0.9566482 (2600)	total: 41.4s	remaining: 6.36s

2800:	test: 0.9569014	best: 0.9569014 (2800)	total: 44.7s	remaining: 3.17s

2999:	test: 0.9571293	best: 0.9571293 (2999)	total: 47.9s	remaining: 0us
bestTest = 0.9571292996
bestIteration = 2999
Fold 0: AUC = 0.95713

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.9059497	best: 0.9059497 (0)	total: 16.2ms	remaining: 48.6s

200:	test: 0.9367236	best: 0.9367236 (200)	total: 3.13s	remaining: 43.7s

400:	test: 0.9430589	best: 0.9430589 (400)	total: 6.25s	remaining: 40.5s

600:	test: 0.9469939	best: 0.9469939 (600)	total: 9.37s	remaining: 37.4s

800:	test: 0.9497333	best: 0.9497333 (800)	total: 12.5s	remaining: 34.3s

1000:	test: 0.9515945	best: 0.9515945 (1000)	total: 15.6s	remaining: 31.1s

1200:	test: 0.9529793	best: 0.9529793 (1200)	total: 18.8s	remaining: 28.1s

1400:	test: 0.9539974	best: 0.9539974 (1400)	total: 22s	remaining: 25.1s

1600:	test: 0.9547921	best: 0.9547921 (1600)	total: 25.2s	remaining: 22s

1800:	test: 0.9554536	best: 0.9554536 (1800)	total: 28.4s	remaining: 18.9s

2000:	test: 0.9559704	best: 0.9559704 (2000)	total: 31.6s	remaining: 15.8s

2200:	test: 0.9564556	best: 0.9564556 (2200)	total: 34.9s	remaining: 12.7s

2400:	test: 0.9568044	best: 0.9568044 (2400)	total: 38.1s	remaining: 9.5s

2600:	test: 0.9571196	best: 0.9571196 (2600)	total: 41.2s	remaining: 6.32s

2800:	test: 0.9573608	best: 0.9573608 (2800)	total: 44.4s	remaining: 3.15s

2999:	test: 0.9575753	best: 0.9575753 (2999)	total: 47.6s	remaining: 0us
bestTest = 0.9575752616
bestIteration = 2999
Fold 1: AUC = 0.95758

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.9055412	best: 0.9055412 (0)	total: 16.2ms	remaining: 48.5s

200:	test: 0.9371468	best: 0.9371468 (200)	total: 3.2s	remaining: 44.5s

400:	test: 0.9432067	best: 0.9432067 (400)	total: 6.32s	remaining: 41s

600:	test: 0.9473677	best: 0.9473677 (600)	total: 9.51s	remaining: 38s

800:	test: 0.9500830	best: 0.9500830 (800)	total: 12.7s	remaining: 34.9s

1000:	test: 0.9519514	best: 0.9519514 (1000)	total: 15.9s	remaining: 31.8s

1200:	test: 0.9533853	best: 0.9533853 (1200)	total: 19.1s	remaining: 28.7s

1400:	test: 0.9544460	best: 0.9544460 (1400)	total: 22.3s	remaining: 25.5s

1600:	test: 0.9552488	best: 0.9552488 (1600)	total: 25.6s	remaining: 22.3s

1800:	test: 0.9558576	best: 0.9558576 (1800)	total: 28.8s	remaining: 19.2s

2000:	test: 0.9564127	best: 0.9564127 (2000)	total: 32s	remaining: 16s

2200:	test: 0.9568473	best: 0.9568473 (2200)	total: 35.2s	remaining: 12.8s

2400:	test: 0.9571679	best: 0.9571679 (2400)	total: 38.4s	remaining: 9.59s

2600:	test: 0.9574697	best: 0.9574697 (2600)	total: 41.7s	remaining: 6.39s

2800:	test: 0.9576786	best: 0.9576787 (2799)	total: 44.8s	remaining: 3.18s

2999:	test: 0.9578596	best: 0.9578596 (2999)	total: 47.9s	remaining: 0us
bestTest = 0.9578596354
bestIteration = 2999
Fold 2: AUC = 0.95786

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.9045729	best: 0.9045729 (0)	total: 16.4ms	remaining: 49.1s

200:	test: 0.9367955	best: 0.9367955 (200)	total: 3.14s	remaining: 43.7s

400:	test: 0.9430104	best: 0.9430104 (400)	total: 6.26s	remaining: 40.6s

600:	test: 0.9472759	best: 0.9472759 (600)	total: 9.37s	remaining: 37.4s

800:	test: 0.9499104	best: 0.9499104 (800)	total: 12.5s	remaining: 34.3s

1000:	test: 0.9519252	best: 0.9519252 (1000)	total: 15.6s	remaining: 31.2s

1200:	test: 0.9533111	best: 0.9533111 (1200)	total: 18.7s	remaining: 28s

1400:	test: 0.9542774	best: 0.9542774 (1400)	total: 21.8s	remaining: 24.9s

1600:	test: 0.9551864	best: 0.9551864 (1600)	total: 25s	remaining: 21.8s

1800:	test: 0.9558593	best: 0.9558593 (1800)	total: 28.1s	remaining: 18.7s

2000:	test: 0.9563823	best: 0.9563823 (2000)	total: 31.2s	remaining: 15.6s

2200:	test: 0.9568751	best: 0.9568759 (2199)	total: 34.3s	remaining: 12.5s

2400:	test: 0.9572520	best: 0.9572520 (2400)	total: 37.4s	remaining: 9.34s

2600:	test: 0.9575811	best: 0.9575811 (2600)	total: 40.6s	remaining: 6.22s

2800:	test: 0.9578698	best: 0.9578698 (2800)	total: 43.7s	remaining: 3.1s

2999:	test: 0.9580963	best: 0.9580966 (2998)	total: 46.8s	remaining: 0us
bestTest = 0.9580966234
bestIteration = 2998
Shrink model to first 2999 iterations.
Fold 3: AUC = 0.95810

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.9051698	best: 0.9051698 (0)	total: 16.2ms	remaining: 48.7s

200:	test: 0.9373551	best: 0.9373551 (200)	total: 3.14s	remaining: 43.7s

400:	test: 0.9437866	best: 0.9437866 (400)	total: 6.25s	remaining: 40.5s

600:	test: 0.9475772	best: 0.9475772 (600)	total: 9.37s	remaining: 37.4s

800:	test: 0.9500959	best: 0.9500959 (800)	total: 12.5s	remaining: 34.3s

1000:	test: 0.9518950	best: 0.9518950 (1000)	total: 15.6s	remaining: 31.2s

1200:	test: 0.9532821	best: 0.9532821 (1200)	total: 18.7s	remaining: 28s

1400:	test: 0.9543557	best: 0.9543557 (1400)	total: 21.8s	remaining: 24.9s

1600:	test: 0.9551657	best: 0.9551657 (1600)	total: 25s	remaining: 21.8s

1800:	test: 0.9558626	best: 0.9558626 (1800)	total: 28.1s	remaining: 18.7s

2000:	test: 0.9563868	best: 0.9563868 (2000)	total: 31.2s	remaining: 15.6s

2200:	test: 0.9567989	best: 0.9567989 (2200)	total: 34.3s	remaining: 12.5s

2400:	test: 0.9571389	best: 0.9571389 (2400)	total: 37.4s	remaining: 9.34s

2600:	test: 0.9574229	best: 0.9574229 (2600)	total: 40.6s	remaining: 6.22s

2800:	test: 0.9576746	best: 0.9576746 (2800)	total: 43.7s	remaining: 3.1s

2999:	test: 0.9578860	best: 0.9578860 (2999)	total: 46.8s	remaining: 0us
bestTest = 0.9578860402
bestIteration = 2999
Fold 4: AUC = 0.95789

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.9066749	best: 0.9066749 (0)	total: 16.2ms	remaining: 48.6s

200:	test: 0.9388458	best: 0.9388458 (200)	total: 3.13s	remaining: 43.7s

400:	test: 0.9448386	best: 0.9448386 (400)	total: 6.25s	remaining: 40.5s

600:	test: 0.9487221	best: 0.9487221 (600)	total: 9.36s	remaining: 37.4s

800:	test: 0.9511262	best: 0.9511262 (800)	total: 12.5s	remaining: 34.2s

1000:	test: 0.9528906	best: 0.9528906 (1000)	total: 15.6s	remaining: 31.1s

1200:	test: 0.9542664	best: 0.9542664 (1200)	total: 18.7s	remaining: 28s

1400:	test: 0.9552742	best: 0.9552742 (1400)	total: 21.8s	remaining: 24.9s

1600:	test: 0.9560303	best: 0.9560303 (1600)	total: 24.9s	remaining: 21.8s

1800:	test: 0.9567199	best: 0.9567199 (1800)	total: 28.1s	remaining: 18.7s

2000:	test: 0.9572306	best: 0.9572306 (2000)	total: 31.2s	remaining: 15.6s

2200:	test: 0.9576363	best: 0.9576363 (2200)	total: 34.3s	remaining: 12.5s

2400:	test: 0.9579423	best: 0.9579423 (2400)	total: 37.4s	remaining: 9.34s

2600:	test: 0.9582632	best: 0.9582632 (2600)	total: 40.6s	remaining: 6.22s

2800:	test: 0.9585226	best: 0.9585226 (2800)	total: 43.7s	remaining: 3.1s

2999:	test: 0.9587578	best: 0.9587578 (2999)	total: 46.8s	remaining: 0us
bestTest = 0.9587577581
bestIteration = 2999
Fold 5: AUC = 0.95876

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.9065269	best: 0.9065269 (0)	total: 16.3ms	remaining: 48.8s

200:	test: 0.9378655	best: 0.9378655 (200)	total: 3.15s	remaining: 43.9s

400:	test: 0.9443049	best: 0.9443049 (400)	total: 6.28s	remaining: 40.7s

600:	test: 0.9481815	best: 0.9481815 (600)	total: 9.41s	remaining: 37.6s

800:	test: 0.9509871	best: 0.9509871 (800)	total: 12.5s	remaining: 34.4s

1000:	test: 0.9527593	best: 0.9527593 (1000)	total: 15.7s	remaining: 31.3s

1200:	test: 0.9542065	best: 0.9542065 (1200)	total: 18.8s	remaining: 28.1s

1400:	test: 0.9552656	best: 0.9552656 (1400)	total: 21.9s	remaining: 25s

1600:	test: 0.9560561	best: 0.9560561 (1600)	total: 25s	remaining: 21.9s

1800:	test: 0.9567165	best: 0.9567165 (1800)	total: 28.2s	remaining: 18.8s

2000:	test: 0.9572049	best: 0.9572049 (2000)	total: 31.3s	remaining: 15.6s

2200:	test: 0.9576300	best: 0.9576302 (2199)	total: 34.4s	remaining: 12.5s

2400:	test: 0.9579683	best: 0.9579683 (2400)	total: 37.6s	remaining: 9.37s

2600:	test: 0.9582833	best: 0.9582833 (2600)	total: 40.7s	remaining: 6.24s

2800:	test: 0.9585342	best: 0.9585345 (2799)	total: 43.8s	remaining: 3.11s

2999:	test: 0.9587314	best: 0.9587314 (2999)	total: 46.9s	remaining: 0us
bestTest = 0.9587313533
bestIteration = 2999
Fold 6: AUC = 0.95873

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.9069116	best: 0.9069116 (0)	total: 16.3ms	remaining: 48.8s

200:	test: 0.9389547	best: 0.9389547 (200)	total: 3.15s	remaining: 43.8s

400:	test: 0.9450074	best: 0.9450074 (400)	total: 6.27s	remaining: 40.7s

600:	test: 0.9489870	best: 0.9489870 (600)	total: 9.39s	remaining: 37.5s

800:	test: 0.9515568	best: 0.9515568 (800)	total: 12.5s	remaining: 34.4s

1000:	test: 0.9533478	best: 0.9533478 (1000)	total: 15.6s	remaining: 31.2s

1200:	test: 0.9546812	best: 0.9546812 (1200)	total: 18.8s	remaining: 28.1s

1400:	test: 0.9556383	best: 0.9556383 (1400)	total: 21.9s	remaining: 25s

1600:	test: 0.9564204	best: 0.9564204 (1600)	total: 25s	remaining: 21.9s

1800:	test: 0.9570761	best: 0.9570761 (1800)	total: 28.2s	remaining: 18.7s

2000:	test: 0.9575812	best: 0.9575812 (2000)	total: 31.3s	remaining: 15.6s

2200:	test: 0.9579863	best: 0.9579863 (2200)	total: 34.4s	remaining: 12.5s

2400:	test: 0.9583166	best: 0.9583166 (2400)	total: 37.6s	remaining: 9.38s

2600:	test: 0.9586361	best: 0.9586362 (2598)	total: 40.7s	remaining: 6.25s

2800:	test: 0.9588802	best: 0.9588802 (2798)	total: 43.9s	remaining: 3.12s

2999:	test: 0.9590781	best: 0.9590781 (2999)	total: 47.1s	remaining: 0us
bestTest = 0.9590781331
bestIteration = 2999
Fold 7: AUC = 0.95908

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.9075365	best: 0.9075365 (0)	total: 16.3ms	remaining: 48.9s

200:	test: 0.9383392	best: 0.9383392 (200)	total: 3.14s	remaining: 43.7s

400:	test: 0.9448484	best: 0.9448484 (400)	total: 6.26s	remaining: 40.6s

600:	test: 0.9486340	best: 0.9486340 (600)	total: 9.38s	remaining: 37.4s

800:	test: 0.9511185	best: 0.9511185 (800)	total: 12.5s	remaining: 34.3s

1000:	test: 0.9529815	best: 0.9529815 (1000)	total: 15.6s	remaining: 31.2s

1200:	test: 0.9543539	best: 0.9543539 (1200)	total: 18.7s	remaining: 28s

1400:	test: 0.9554267	best: 0.9554267 (1400)	total: 21.8s	remaining: 24.9s

1600:	test: 0.9562840	best: 0.9562840 (1600)	total: 25s	remaining: 21.8s

1800:	test: 0.9569672	best: 0.9569672 (1800)	total: 28.1s	remaining: 18.7s

2000:	test: 0.9574867	best: 0.9574869 (1999)	total: 31.2s	remaining: 15.6s

2200:	test: 0.9579024	best: 0.9579024 (2200)	total: 34.3s	remaining: 12.5s

2400:	test: 0.9582644	best: 0.9582644 (2400)	total: 37.5s	remaining: 9.34s

2600:	test: 0.9585523	best: 0.9585523 (2600)	total: 40.6s	remaining: 6.22s

2800:	test: 0.9588395	best: 0.9588401 (2799)	total: 43.7s	remaining: 3.1s

2999:	test: 0.9590722	best: 0.9590722 (2999)	total: 46.8s	remaining: 0us
bestTest = 0.9590721726
bestIteration = 2999
Fold 8: AUC = 0.95907

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.9046344	best: 0.9046344 (0)	total: 16.3ms	remaining: 48.9s

200:	test: 0.9364924	best: 0.9364924 (200)	total: 3.16s	remaining: 44s

400:	test: 0.9425805	best: 0.9425805 (400)	total: 6.3s	remaining: 40.8s

600:	test: 0.9465104	best: 0.9465104 (600)	total: 9.44s	remaining: 37.7s

800:	test: 0.9490403	best: 0.9490403 (800)	total: 12.6s	remaining: 34.5s

1000:	test: 0.9508451	best: 0.9508451 (1000)	total: 15.7s	remaining: 31.4s

1200:	test: 0.9521418	best: 0.9521418 (1200)	total: 18.8s	remaining: 28.2s

1400:	test: 0.9531716	best: 0.9531716 (1400)	total: 22s	remaining: 25.1s

1600:	test: 0.9540128	best: 0.9540128 (1600)	total: 25.1s	remaining: 22s

1800:	test: 0.9546656	best: 0.9546656 (1800)	total: 28.3s	remaining: 18.8s

2000:	test: 0.9552317	best: 0.9552325 (1998)	total: 31.4s	remaining: 15.7s

2200:	test: 0.9557105	best: 0.9557105 (2200)	total: 34.6s	remaining: 12.5s

2400:	test: 0.9560466	best: 0.9560466 (2400)	total: 37.7s	remaining: 9.4s

2600:	test: 0.9563299	best: 0.9563299 (2600)	total: 40.8s	remaining: 6.27s

2800:	test: 0.9565932	best: 0.9565932 (2800)	total: 44s	remaining: 3.13s

2999:	test: 0.9568199	best: 0.9568199 (2999)	total: 47.1s	remaining: 0us
bestTest = 0.9568198919
bestIteration = 2999
Fold 9: AUC = 0.95682

## 7. Overall CV score

In [8]:
overall_auc = roc_auc_score(y, oof_preds)
print(f"Mean fold AUC: {np.mean(fold_scores):.5f} +/- {np.std(fold_scores):.5f}")
print(f"Overall OOF AUC: {overall_auc:.5f}")

Mean fold AUC: 0.95810 +/- 0.00075
Overall OOF AUC: 0.95810

## 8. Feature importance

Sanity check on which features CatBoost is relying on most.

In [9]:
importances = models[-1].get_feature_importance(train_pool)
importance_df = pd.DataFrame({
    "feature": FEATURES,
    "importance": importances,
}).sort_values("importance", ascending=False)

importance_df.plot(x="feature", y="importance", kind="barh", figsize=(8, 5), legend=False)
plt.gca().invert_yaxis()
plt.title("CatBoost feature importance (last fold)")
plt.tight_layout()
plt.savefig("feature_importance.png", bbox_inches="tight")
plt.close()

importance_df

                    feature  importance
1   daily_screen_time_hours   26.423650
8       weekend_screen_time   24.213976
2        social_media_hours   18.279943
6     notifications_per_day   11.815003
7         app_opens_per_day   11.144608
4          work_study_hours    3.394998
3              gaming_hours    2.525029
0                       age    1.081682
5               sleep_hours    1.024300
9                    gender    0.064254
10             stress_level    0.022611
11     academic_work_impact    0.009945

## 9. Build submission

In [10]:
submission = test[[ID_COL]].copy()
submission[TARGET] = test_preds
submission.to_csv("submission.csv", index=False)
submission.head()

       id  addicted_label
0  691369        0.999294
1  691370        0.944154
2  691371        0.970362
3  691372        0.973873
4  691373        0.996992